### ISSUE TITLE
[Windows] Respect icon path

### ISSUE THREAD

**Issue by nickrandolph** [unoplatform/uno.resizetizer#19]
See comment in PR: https://github.com/unoplatform/uno.resizetizer/pull/15#discussion_r1063051120

Currently all icons are generated in the Images folder in the package
Icons should be generated and added to the package in the same folder that the source image was in. Eg if the source file was in the MyIcons folder, the generated files should be found in the MyIcons folder in the application package

**Comment by ADD-David-Antolin** [comment]
In respect to this issue, in [here](https://github.com/unoplatform/uno.resizetizer/blob/e23dfa53da77e48510173e99a29c260b08b826f5/src/Resizetizer/src/Resizer.cs#L39) OutputPath it is taken into account to generate the destination file, but in the generate pakage.appxmanifest [task](https://github.com/unoplatform/uno.resizetizer/blob/e23dfa53da77e48510173e99a29c260b08b826f5/src/Resizetizer/src/GeneratePackageAppxManifest.cs#L162) it is not, so when the AppIcon is in a subfolder (`OutputPath` is neither null nor empty) the `package.appxmanifest` does not find it because it does not have the `OutputPath` added to the uris/paths.
